version: "3.2"

services:
 
    php:
        container_name: mage_phpfpm
        image: trydock/mage23-php
        ports:
            - 9000:9000
        volumes:
            - ./htdocs:/var/www/html
            - ./configs/php-fpm/www.conf:/etc/php7/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        networks:
            - magenet_internal

    nginx:
        container_name: mage_websrv
        image: nginx:1.14.2
        ports:
            - 80:80
        volumes:
            - ./htdocs:/var/www/html
            - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./configs/nginx/magento_include.conf:/etc/nginx/magento_include.conf
            - ./configs/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./configs/nginx/conf.d/php.conf:/etc/nginx/conf.d/php.conf
        depends_on:
            - php
        restart: always
        networks:
            - magenet_internal
            - magenet_external

    mysql:
        container_name: mage_mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        networks:
            - magenet_internal

networks:
    magenet_external:
        driver: bridge
    magenet_internal:
        driver: bridge